kind: pipeline
name: default

steps:
- name: backend-build
  image: composer:1.8
  commands:
  - cd backend
  - composer install --ignore-platform-reqs
  - composer openapi

- name: backend-test-71
  image: php:7.1
  environment:
    BRAVECORE_APP_ENV: dev
    BRAVECORE_TEST_DATABASE_URL: mysql://root:@database/test
  commands:
  - docker-php-ext-install pdo_mysql
  - cd backend
  - vendor/bin/phpunit

- name: backend-test-72
  image: php:7.2
  environment:
    BRAVECORE_APP_ENV: dev
    BRAVECORE_TEST_DATABASE_URL: mysql://root:@database/test
  commands:
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - docker-php-ext-install pdo_mysql
  - cd backend
  - vendor/bin/phpunit

- name: generate-api-client
  image: openjdk:11
  commands:
  - cd frontend
  - ./swagger.sh

- name: frontend-build
  image: node:10
  commands:
  - cd frontend
  - npm install
  - npm run build:prod
  - cd ../web
  - npm install

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  environment:
    SONAR_HOST:
      from_secret: sonar_host
    SONAR_TOKEN:
      from_secret: sonar_token
  settings:
    sources: backend/src/classes,frontend/src

- name: distribution
  image: composer:1.8
  environment:
    BRAVECORE_APP_ENV: prod
    BRAVECORE_DATABASE_URL: mysql://root:@database/test
  commands:
  - docker-php-ext-install pdo_mysql
  - cd backend
  - composer install --ignore-platform-reqs --no-dev --optimize-autoloader --no-interaction
  - vendor/bin/doctrine orm:generate-proxies
  - cd ..
  - mkdir -p dist/brvneucore
  - cp -R backend dist/brvneucore/backend
  - cp -R doc dist/brvneucore/doc
  - cp -R web dist/brvneucore/web
  - cp LICENSE dist/brvneucore/LICENSE
  - cp CHANGELOG.md dist/brvneucore/CHANGELOG.md
  - cp README.md dist/brvneucore/README.md
  - cd dist
  - tar -czf brvneucore-${DRONE_TAG}.tar.gz brvneucore
  - sha256sum brvneucore-${DRONE_TAG}.tar.gz > brvneucore-${DRONE_TAG}.sha256
  when:
    event: tag

- name: release
  image: plugins/gitea-release:1.1
  settings:
    api_key:
      from_secret: GITEA_TOKEN
    base_url:
      from_secret: GITEA_URL
    files:
    - dist/*.gz
    - dist/*.txt
  when:
    event: tag

services:
- name: database
  image: mariadb:10.1
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test
