build:
    project_setup:
        before:
            - "cd backend"
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=var/logs/clover.xml'
                        coverage:
                            file: 'var/logs/clover.xml'
                            format: 'clover'
            environment:
                php: 7.1.12
checks:
    php: true
coding_style:
    php: {  }
filter: {  }
