build:
    dependencies: 
        override:
            - cd backend
            - composer install --ignore-platform-reqs --no-interaction --no-scripts

    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
            environment:
                php: 7.1.12
checks:
    php: true
coding_style:
    php: {  }
filter: {  }
tools:
    external_code_coverage:
        timeout: 1800    # Timeout in seconds.
