language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

addons:
  mariadb: '10.1'

env:
  global:
    - BRAVECORE_APP_ENV=dev
    - BRAVECORE_DATABASE_URL=mysql://travis:@127.0.0.1/brvneucore
    - BRAVECORE_TEST_DATABASE_URL=mysql://travis:@127.0.0.1/brvneucore
    - CC_TEST_REPORTER_ID=c84a0a91cfa81997bac8afcd50ef25ca4bc07f86a83f061fdce4646ac62ca986
  matrix:
    - NODE_VERSION="8.14.0"
    - NODE_VERSION="10.14.2"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  exclude:
    - php: 7.1
      env: NODE_VERSION="10.14.2"
    - php: 7.2
      env: NODE_VERSION="8.14.0"
    - php: 7.3
      env: NODE_VERSION="8.14.0"
    - php: nightly
      env: NODE_VERSION="8.14.0"

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS brvneucore;'
  - nvm install $NODE_VERSION

install:
  - ./install.sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > backend/cc-test-reporter
  - chmod +x backend/cc-test-reporter
  - if [ $(phpenv version-name) = "7.2" ]; then backend/cc-test-reporter before-build; fi

script:
  - backend/vendor/bin/phpunit -c backend/phpunit.xml

after_script:
  - mkdir -p build/logs
  - cp backend/var/logs/clover.xml build/logs/clover.xml
  - if [ $(phpenv version-name) = "7.2" ]; then backend/cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT; fi
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover backend/var/logs/clover.xml
