dist: xenial

language: php

git:
  depth: false

php:
  - "7.2"
  #- "7.3"
  #- "7.4"
  #- nightly

addons:
  sonarcloud:
    organization: "tkhamez-github"
    token:
      secure: "BcQunnP8ZpSK5IXzb1g9QCjSfF4fSaA25UwxEGcLlCwc6wa212bWAfdbmslN1xP31xaS3/VT8r9myiWPbRKw27y2k9mXj64oV/5EsRds34UjDOqwQCJnuMoc0miYkEF36zy1eQEf115LgsmQmUaN9bNYh2Y2Q2M+LbqFM8f1kuzaZXetYRKhKNlN2QYF529BYsGvX2asjlu91D8e1psnrcZ/qxDpf8MSjGU2ODXY/HLGVhLOasuXy1fjEDuFPb80TD1n9cOp1Tuf/zLc3dTjtLKNGeqnhVhzXhV7C6cLe2TYis3NKkCxVTPEg/+7OOUXP8sEy+xsA7PZ1Sc7d54qhZ0d2/K8eIzz05mX0fwMl14Nxi6L9WnYsRFwoFKQrKspiAhtsLcwCbDQhXWkgQZJKgyqK9qh61WgKRtTjG6rbZtyGpAu1ZxXbt/BEKXQEFflAc1MC1U6sFpdw2CyHA05WKuHN2W+rsqk0d0mIghQIpGXgjfdDgQLcdbXLFYln7cL3qK6ai4cctQbRWvbfmbxBCM1oBAa1gM674r9S89dXCuh1abSAaQIW2fpiUNrxt70ZqZxaNlb0iU4hTdgbVoob/bi5v3/hc8TWEhZ4xHmaJQ7k1sXxjDjeQlR0A0tZ5Xa0/3Xi4HIhGfeketooIVvGIiHaoS/wKJYv94mAwtdfQo="

env:
  global:
    - BRAVECORE_APP_ENV=dev
    - BRAVECORE_DATABASE_URL=mysql://neu:core@localhost/neucore
    - BRAVECORE_TEST_DATABASE_URL=mysql://neu:core@localhost/neucore
  matrix:
    #- NODE_VERSION="10.13.0" DB=mysql:5.7
    #- NODE_VERSION="10.13.0" DB=mysql:8.0
    - NODE_VERSION="10.16.3" DB=mariadb:10.2
    #- NODE_VERSION="10.16.3" DB=mariadb:10.3
    #- NODE_VERSION="12.12.0" DB=mariadb:10.4

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  exclude:
    #- php: "7.2"
    #- php: "7.3"
    #- php: "7.4"
    #- php: nightly
  include:
    #- php: "7.2"
    #  env: NODE_VERSION="10.13.0" DB=mysql:5.7
    #  services:
    #    - mysql
    #- php: "7.2"
    #  env: NODE_VERSION="10.13.0" DB=mysql:8.0
    - php: "7.2"
      env: NODE_VERSION="10.16.3" DB=mariadb:10.2
      addons:
        mariadb: "10.2"
    #- php: "7.3"
    #  env: NODE_VERSION="10.16.3" DB=mariadb:10.2
    #  addons:
    #    mariadb: "10.2"
    #- php: "7.3"
    #  env: NODE_VERSION="10.16.3" DB=mariadb:10.3
    #  addons:
    #    mariadb: "10.3"
    #- php: "7.4"
    #  env: NODE_VERSION="12.12.0" DB=mariadb:10.4
    #  addons:
    #    mariadb: "10.4"
    #- php: nightly
    #  env: NODE_VERSION="12.12.0" DB=mariadb:10.4
    #  addons:
    #    mariadb: "10.4"

before_install:
  - if [[ "$DB" == "mysql:8.0" ]]; then wget https://repo.mysql.com/mysql-apt-config_0.8.13-1_all.deb; fi
  - if [[ "$DB" == "mysql:8.0" ]]; then sudo dpkg -i mysql-apt-config_0.8.13-1_all.deb; fi
  - if [[ "$DB" == "mysql:8.0" ]]; then sudo apt-get update -q; fi
  - if [[ "$DB" == "mysql:8.0" ]]; then sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server; fi
  - if [[ "$DB" == "mysql:8.0" ]]; then sudo systemctl restart mysql; fi
  - if [[ "$DB" == "mysql:8.0" ]]; then sudo mysql_upgrade; fi
  - mysql --version
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS neucore;'
  - if [[ "$DB" == "mysql:8.0" ]]; then mysql -e "CREATE USER 'neu'@'localhost' IDENTIFIED WITH mysql_native_password BY 'core';"; fi
  - if [[ "$DB" == "mariadb:10.4" ]]; then sudo mysql -e "CREATE USER neu@localhost IDENTIFIED VIA mysql_native_password USING PASSWORD('core');"; fi
  - if [[ "$DB" != "mysql:8.0" && "$DB" != "mariadb:10.4" ]]; then mysql -e "CREATE USER 'neu'@'localhost' IDENTIFIED BY 'core';"; fi
  - sudo mysql -e "GRANT ALL PRIVILEGES ON neucore.* TO 'neu'@'localhost'"
  - nvm install $NODE_VERSION
  - node -v
  - npm -v

install:
  - ./install.sh

script:
  - backend/vendor/bin/phpunit -c backend/phpunit.xml
  #- if [[ $(phpenv version-name) == "7.2" ]] && [[ "$DB" == "mysql:8.0" ]] && [[ $TRAVIS_REPO_SLUG == "tkhamez/neucore" ]]; then sonar-scanner; fi

before_deploy:
  - ./dist.sh $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: "pZwRqHKddvjzD8GtO+wUh26RTzjpQOZzS3Fmi4JH7dIz+dijxFjZxkOgsRdL2yszvaS00PIkC9Rd4SnEmG1DNtVq2OHCXq1XZzs4Ms36bWUn7dMNDNPD9XtqFy3o/GZ4TIqFoXeXKj9nToPcNT5l2W3bK5kEzsl0xS0qm5GyLgCZBG8SBnuyM3GQk49J0rfmmGhTPULPBsA9t+GieykduBUhV7DG+4PmfqTR828Np6K8wW+21Q42Ac6g7UC8oLGenk8SYvH/Z45hc5CLOBVU6HxtnmbEMGKfRuO4sWvcyOImivPpwNaSD77XPePg7QhOKWIS/aaicVnijhh8WB4B7zg8QbQI1xMwfRGdhSJ2tRWiWK/hdNBgOFcn8JG4zPb8aTIJ6UqKtiJ2EXT1KnFq96Cux6mxNs5fQOBs8v1lV65WEFpFhqNRcUJ7m5KV/rHdopCcX1b7IYzw5qaZdYuXAY6D7yTATnKvPzYRHap8brnby27k2liUZjzBQNdBk9Zs7OWDnXvEyZL7sNjRxMPvBKrWlxDV6OQH8iZ3hASl4+Cy5sRqSSS8YnLv2ldBFtrjMbIe55DTsGjYTN+pxPp0o6UI44zfW5p98hRO2H+euiT6seazHo19ebtiUemzZLGkB/rqP4rCMm99NTBST3EC2GIjAczmk30b0dawtL2S7ow="
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: tkhamez/neucore
    tags: true
