language: php

php:
  - '7.1'
  - '7.2'

addons:
  mariadb: '10.1'

env:
  global:
    - BRAVECORE_APP_ENV=dev
    - BRAVECORE_DATABASE_URL=mysql://travis:@127.0.0.1/brvneucore
    - BRAVECORE_TEST_DATABASE_URL=mysql://travis:@127.0.0.1/brvneucore
    - BRAVECORE_EVE_CLIENT_ID=123
    - BRAVECORE_EVE_SECRET_KEY=abc
    - BRAVECORE_EVE_CALLBACK_URL=https://brave.core.tld/api/user/auth/callback
    - CC_TEST_REPORTER_ID=c84a0a91cfa81997bac8afcd50ef25ca4bc07f86a83f061fdce4646ac62ca986

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.2'

before_install:
  - phpenv config-add config/travis.ini
  - mysql -e 'CREATE DATABASE IF NOT EXISTS brvneucore;'

install:
  - ./install.sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - cd backend && ./vendor/bin/phpunit
  - cd .. && npm --prefix frontend run check

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover backend/var/logs/clover.xml
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

