language: php

php:
  - '7.1'
  - '7.2'

addons:
  mariadb: '10.1'

env:
  global:
    - BRAVECORE_APP_ENV=prod
    - BRAVECORE_DATABASE_URL=mysql://travis:@127.0.0.1/brvneucore
    - BRAVECORE_TEST_DATABASE_URL=mysql://travis:@127.0.0.1/brvneucore
    - BRAVECORE_EVE_CLIENT_ID=123
    - BRAVECORE_EVE_SECRET_KEY=abc
    - BRAVECORE_EVE_CALLBACK_URL=https://brave.core.tld/api/user/auth/callback

before_install:
  - phpenv config-add config/travis.ini
  - mysql -e 'CREATE DATABASE IF NOT EXISTS brvneucore;'

install:
  - ./install.sh

script:
  - cd backend && ./vendor/bin/phpunit
  - cd .. && npm --prefix frontend run check

after_success:
  - bash <(curl -s https://codecov.io/bash)
