dist: xenial

language: php

git:
  depth: false

php:
  - "7.2"
  - "7.3"
  - "7.4"
  - nightly

addons:
  sonarcloud:
    organization: "tkhamez-github"
    token:
      secure: "LN/qvsQK7T3uA4LDIignXniLgwzLTKEPmzMr4R4rb2t2LWEww4J4OlI2Rs3jfZf1EoMGQ8CFbob/6OCFWaLWwQhiHRSlQvXcBeZSWBfrtsmweb3Yn+PsW6MsX/qEEKq0lxmyHWAkv2q/XhJyAGksM5JRsgnZKqcJbq6R54oyUPvQJHNsZaGJaW4Co9CvpkOdD3DBy5/5a83NHkpfnQEVa5LMvotg2Uw9hY2iup/GyL4pmF0LNGozyf7etyho7Dsr7O5Ay8q6SZdMU5HIGAYU/UpMX9fTX+IISfq8/cO6T/NR9hnsx5ihxYc5TZIjEqsq9e3l/IA9K/qBqgZaAznb6A4/70NbpqD7ML+S7DJLl9G0FhzZx81zr8UuH3LK4WA33wnDQBT6LaSCM+Hz6TTh3c3WKwuX/WvMjabs7LMhmHD34AxD9pg7nWJpb+5xyBZdfZ/vjWbzWsrgYBb51wGfTEfZNnVHvAKoXlSL3GhvTdJp9f8D5VYoFqSWPiHkXrmepHnnx2MyRgyySLQXNDtAdF8FM3PkoqFcEzy8nYLBnwmyZIofpAAtiPX7I78BfY3gZvdXzTvMGBjZjkvTdtqRhB5HRenESiCBAbjsxlYS06Tyi5JeGWXn94nYi07SAbyIAQI1n8m2gZRoC6xNJMQTNgqYNNTW4KfXm5JiR5DvKqM="

services:
  - mysql

env:
  global:
    - BRAVECORE_APP_ENV=dev
    - BRAVECORE_DATABASE_URL=mysql://neu:core@localhost/neucore
    - BRAVECORE_TEST_DATABASE_URL=mysql://neu:core@localhost/neucore
  matrix:
    - NODE_VERSION="10.13.0" DB=mysql:5.7

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  exclude:
    - php: "7.3"
      env: NODE_VERSION="10.13.0" DB=mysql:5.7
    - php: "7.4"
      env: NODE_VERSION="10.13.0" DB=mysql:5.7
  include:
    - php: "7.2"
      env:
        - NODE_VERSION="10.16.3" DB=mysql:8.0
      before_install:
        - wget https://repo.mysql.com/mysql-apt-config_0.8.13-1_all.deb
        - sudo dpkg -i mysql-apt-config_0.8.13-1_all.deb
        - sudo apt-get update -q
        - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
        - sudo systemctl restart mysql
        - sudo mysql_upgrade
    - php: "7.3"
      env:
        - NODE_VERSION="10.20.1" DB=mariadb:10.2
      addons:
        mariadb: "10.2"
    - php: "7.3"
      env:
        - NODE_VERSION="12.13.0" DB=mariadb:10.3
      addons:
        mariadb: "10.3"
    - php: "7.4"
      env:
        - NODE_VERSION="12.16.2" DB=mariadb:10.4
      addons:
        mariadb: "10.4"

install:
  - mysql --version
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS neucore;'
  - if [[ "$DB" == "mysql:8.0" ]]; then mysql -e "CREATE USER 'neu'@'localhost' IDENTIFIED WITH mysql_native_password BY 'core';"; fi
  - if [[ "$DB" == "mariadb:10.4" ]]; then sudo mysql -e "CREATE USER neu@localhost IDENTIFIED VIA mysql_native_password USING PASSWORD('core');"; fi
  - if [[ "$DB" != "mysql:8.0" && "$DB" != "mariadb:10.4" ]]; then mysql -e "CREATE USER 'neu'@'localhost' IDENTIFIED BY 'core';"; fi
  - sudo mysql -e "GRANT ALL PRIVILEGES ON neucore.* TO 'neu'@'localhost'"
  - nvm install $NODE_VERSION
  - node -v
  - npm -v
  - ./install.sh

script:
  - backend/vendor/bin/phpunit -c backend/phpunit.xml
  - if [[ $(phpenv version-name) == "7.2" ]] && [[ "$DB" == "mysql:5.7" ]] && [[ $TRAVIS_REPO_SLUG == "tkhamez/neucore" ]]; then sonar-scanner; fi

before_deploy:
  - ./dist.sh $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: "UiG6xuolSwFffwjU4eUmdqb1FJMhxx5kLzjW5t0yl86gGikF6H8wQxdxCKpoY8YdCemOptMz4MHaUk2PnpRfk5vrSzd2csMcNOQlCOUGMAQ35HqR9gRU6NUGpqzTQQ/TDdl3ZSkZJ4h14UMdsl5Cm36BPFyEpBEiQbJg7bSgDWLvDjdrVzgd/HDN++fSuz8EklMVWp3sWtW7HvjyO5H/98Eb9ySSmPdTNEjkmP4UeV+5OvbtRnWwNs8vZP2bjlVmETI59BPQ1A3KW0e+gEEZm54ASrAZUB9/lMGmvbYPQRUv/GB3h6bTh3VO8v4B7eXpZHm2ZQTly9e9VyvpbI6dwHLbtEZdSzSh1VJKO+6UvZni8rjll8s/idfPT6wR/O8FxS1C5d2klt76YvtwrdHF0DujATt1Fx0gmj+8lCXY0XxiVZd/PmBpyvQsPtUSOHetYJZNzznzVKsSztv4UNDESkP1IkR/ILP/pv+eU645OmcLdQ4rfyx/29YBVT3kAXguD4iiTDqfoAtYyVkLLPrsTtt5zxjxDn6pJULLnoSRq2M1JUq9n1vET8QP4KKKAulunxyG+w848OfUV3Dvo3D5KiDu1JorFG0+kmWSIqhTJSDee8Xqna2V+zTijuKiBck9AcFILqYi0tKAr8XhKcRdMG3hnd0Kzd9J1hEnVOSuCLI="
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: tkhamez/neucore
    tags: true
