language: php

php:
  - '7.1'
  - '7.2'
  
matrix:
  allow_failures:
  - php: 7.2

services:
  - mysql

env:
  global:
    - BRAVECORE_APP_ENV=prod
    - BRAVECORE_DATABASE_URL=mysql://travis:@127.0.0.1/brvneucore
    - BRAVECORE_EVE_CLIENT_ID=123
    - BRAVECORE_EVE_SECRET_KEY=abc
    - BRAVECORE_EVE_CALLBACK_URL=https://brave.core.tld/api/user/auth/callback

before_install:
  - phpenv config-add travis.ini
  - mysql -e 'CREATE DATABASE IF NOT EXISTS brvneucore;'

install:
  - ./install.sh

script:
  - cd backend && ./vendor/bin/phpunit
  - cd .. && npm --prefix frontend run check
