language: php

git:
  depth: false

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - nightly

addons:
  mariadb: "10.3"
  sonarcloud:
    organization: "tkhamez-github"
    token:
      secure: "oHFdB27/6RBWXkhyh9Mzt3BRgRSIDnkijLzhOC5TPNpIeXTiqsS+Nw8wJPHSnTvxE0Ck2iBzdNDSqfHgmC6gbKb2XWp3z6qM6xTHPzuQEHqqoVTReIPyK2/6nHrHoYTMkzoQ3U2pGBF8xVvkRly34FR2HBLiYbgIcIYKW0095nWAvITUC/L9YD5pLeIuMsEKjY64417XIyrSWhBru2iqgJDmeluAOp4gb7uAzKbVob+aF9d/VH1+MYGmWhcsccgOWKDPCBLmYbkLs2SFUBObOdU3kjzGzVXc3/+/fC4IrvZxSG2mbHG+bJOjpK5kPh1GUu9DLD41IZDCTColjxI8Kt7OUPxT8yZ42hq0ZtzmWlM5HExEp7bp6dyG9ZC19BuGLxetmzB14d28XJylovt5N+BAzbQNJndWIXcDXPvTIfXGC7eYhOS0BxAJSuCsoxTQR8A22FcUUnA3M3parmzijltkYJPmCIAGp9Qjou5oOeeIqKMpMxcOwst/HrjYTpB74ADLSsbrKOo3ivBHddsXUKjLJby0fIf9j7CtebcgqwyFR2Gm/68amdaqmiiT1Z9/lvsl+bI3/bR+wyhoWioBoTusrUU0/kYjWK3FsL+om7axDzX2hk2WXMXN8l1pNQPha3EcyDX/gatQNilQZfPi4L5mVA+gCsviGALmHxRL/FQ="

env:
  global:
    - BRAVECORE_APP_ENV=dev
    - BRAVECORE_DATABASE_URL=mysql://travis:@127.0.0.1/neucore
    - BRAVECORE_TEST_DATABASE_URL=mysql://travis:@127.0.0.1/neucore
  matrix:
    - NODE_VERSION="8.16.0"
    - NODE_VERSION="10.15.3"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  exclude:
    - php: "7.1"
      env: NODE_VERSION="10.15.3"
    - php: "7.2"
      env: NODE_VERSION="8.16.0"
    - php: "7.3"
      env: NODE_VERSION="8.16.0"
    - php: nightly
      env: NODE_VERSION="8.16.0"

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS neucore;'
  - nvm install $NODE_VERSION

install:
  - ./install.sh

script:
  - backend/vendor/bin/phpunit -c backend/phpunit.xml
  - if [ $(phpenv version-name) = "7.2" ] && [ $TRAVIS_REPO_SLUG = "tkhamez/neucore" ]; then sonar-scanner; fi

before_deploy:
  - ./dist.sh $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: jqugUTZGE34rV35AD/a3M3QqYwv5P9msVDRPtnlG1EVrSM+GkpXJBSJykWVnurmtCaV+3DaPcmDkW/TSpHUukKyodMlddWMz1tC0a5rk8/i+AEWSdosOQ4OjH1q3tB8X7uUGtdIkLwcKtkUCxL13clcVgG+Y12uoov7B3vOKubfx3zuHytRXnumK0awp1iZhxXL7gwIiBDm8iem9vAt3Qn28MMXGayoQ2BJJlJga/r+OBaVhyDNIIFcl465Bk2H246dkd/z9QAH1YFvMJYTjkA4S+BT+HH5jPZVkWCM53UDRYlKGlCyNxkEEZhjSo96ffJzQsfidWqEzNDb/hRFB7Lez0YF27OnH32VPVv0Giy9TDJqfHkTcf7xJoWwO1Akdzeo5ogPLUIMdfiP+fkf2S5/hCecgJIHrvQ7j7YntDEmBWVb+tNxlV198pU80NfdURS9s9ALPDd1qLM6/TsIUHg7MeAVdEnKiF/QeeY0D9rLBaLoje2iP6LZrKqZL+FR/QiaecrYZ0TwrHSLAUc2rFyglW6/AgTUQyjT50Zuju9IytpPkfx+1bnPMNnDmKjISSrrCpw7DmLmnc2BoclQ9H1+vq3y0KnhYHYcdt12gk4Gq+4Bm9OMYvUWwEIQCGssifUzSKyD4nNgcWVCYF7OsfUlz9eLS/99LYKBeljwRK94=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: tkhamez/neucore
    tags: true
