language: php

php:
  - '7.1'

services:
  - mysql

env:
  global:
    - BRAVECORE_APP_ENV=prod
    - BRAVECORE_DATABASE_URL=mysql://travis:@127.0.0.1/brvneucore
    - BRAVECORE_EVE_CLIENT_ID=123
    - BRAVECORE_EVE_SECRET_KEY=abc
    - BRAVECORE_EVE_CALLBACK_URL=https://brave.core.tld/api/user/auth/callback

before_install:
  - echo yes | pecl install apcu-5.1.9
  - phpenv config-add travis.ini
  - mysql -e 'CREATE DATABASE IF NOT EXISTS brvneucore;'
  - wget https://oss.sonatype.org/content/repositories/releases/io/swagger/swagger-codegen-cli/3.0.0-rc0/swagger-codegen-cli-3.0.0-rc0.jar -q -O swagger-codegen.jar

install:
  - composer install
  - composer compile
  - java -jar swagger-codegen.jar generate -i web/swagger.json -l typescript-fetch -o frontend/swagger
  - npm --prefix frontend/swagger i
  - npm --prefix frontend i


script:
  - ./vendor/bin/phpunit
  - npm --prefix frontend run check

