# Creates a development environment

version: '3.5'

services:
  neucore_db:
    container_name: neucore_dev_db
    #image: mariadb:10.2
    image: mariadb:10.6 # LTS
    #image: mariadb:10.8
    #volumes: ["./.db/10.2:/var/lib/mysql"]
    volumes: ["./.db/10.6:/var/lib/mysql"]
    #volumes: ["./.db/10.8:/var/lib/mysql"]
    environment:
      MYSQL_ROOT_PASSWORD: neucore
      MYSQL_USER: neucore
      MYSQL_PASSWORD: neucore
      MYSQL_DATABASE: neucore
    ports: ["30306:3306"]
    networks: [neucore]

  neucore_java:
    container_name: neucore_dev_java
    image: openjdk:11-jre
    volumes: [".:/app"]
    user: ${UID}
    networks: [neucore]

  neucore_node:
    container_name: neucore_dev_node
    build:
      context: doc
      dockerfile: Dockerfile-node
    volumes: [".:/app"]
    environment:
      BACKEND_HOST: http://localhost:8080
    ports: [ "3000:8080" ]
    user: node
    working_dir: /app/frontend
    networks: [neucore]

  neucore_php:
    container_name: neucore_dev_php
    build:
      context: doc
      #dockerfile: Dockerfile-php80-fpm
      #dockerfile: Dockerfile-php81-fpm
      dockerfile: Dockerfile-php82-fpm
    depends_on: [neucore_db]
    volumes: [
        ".:/app",
        #"/path/to/service-plugin:/plugins/plugin-name",
    ]
    environment:
      PHP_IDE_CONFIG: serverName=docker # for PhpStorm
    user: ${UID}
    working_dir: /app/backend
    networks: [neucore]
    dns: [8.8.8.8]

  neucore_http:
    container_name: neucore_dev_http
    image: nginx:1
    depends_on: [neucore_php]
    volumes: [".:/app", "./doc/docker-nginx.conf:/etc/nginx/conf.d/default.conf"]
    ports: ["8080:80"]
    networks: [neucore]

networks:
  neucore:
    name: neucore_dev
