version: '3'

services:

  db:
    container_name: neucore_db
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: neucore
      MYSQL_USER: neucore
      MYSQL_PASSWORD: neucore
      MYSQL_DATABASE: neucore
    ports:
      - 30306:3306

  java:
    container_name: neucore_java
    image: openjdk:11
    volumes:
      - .:/app
    user: ${UID}

  node:
    container_name: neucore_node
    image: node:12
    volumes:
      - .:/app
    user: ${UID}
    working_dir: /app/frontend

  php-fpm:
    container_name: neucore_php-fpm
    build:
      context: doc
      dockerfile: Dockerfile-php-fpm
    depends_on:
      - db
    user: ${UID}
    working_dir: /app/backend
    volumes:
      - .:/app
    environment:
      - NEUCORE_DATABASE_URL=mysql://neucore:neucore@db/neucore
      - NEUCORE_TEST_DATABASE_URL=mysql://neucore:neucore@db/neucore_test

  http:
    container_name: neucore_http
    image: nginx:1
    depends_on:
      - php-fpm
    volumes:
      - .:/app
      - ./doc/docker-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
