version: '3'

services:
  db:
    container_name: neucore_db
    image: mariadb:10.4
    volumes: ["./.mariadb:/var/lib/mysql"]
    user: ${UID}
    environment:
      MYSQL_ROOT_PASSWORD: neucore
      MYSQL_USER: neucore
      MYSQL_PASSWORD: neucore
      MYSQL_DATABASE: neucore
    ports: ["30306:3306"]

  java:
    container_name: neucore_java
    image: openjdk:11
    volumes: [".:/app"]
    user: ${UID}

  node:
    container_name: neucore_node
    image: node:10.16.0-alpine
    #image: node:12.19.0-alpine
    #image: node:14.15.0-alpine
    volumes: [".:/app"]
    user: node
    working_dir: /app/frontend

  php-fpm:
    container_name: neucore_php-fpm
    build:
      context: doc
      #dockerfile: Dockerfile-php73-fpm
      dockerfile: Dockerfile-php74-fpm
      #dockerfile: Dockerfile-php80-fpm
    depends_on: [db]
    volumes: [".:/app"]
    user: ${UID}
    working_dir: /app/backend

  http:
    container_name: neucore_http
    image: nginx:1
    depends_on: [php-fpm]
    volumes: [".:/app", "./doc/docker-nginx.conf:/etc/nginx/conf.d/default.conf"]
    ports: ["8080:80"]
