version: '3'

services:

  db:
    container_name: neucore_db
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: neucore
      MYSQL_USER: neucore
      MYSQL_PASSWORD: neucore
      MYSQL_DATABASE: neucore
    ports:
      - 30306:3306

  composer:
    container_name: neucore_composer
    build:
      context: .
      dockerfile: Dockerfile-composer
    depends_on:
      - db
    volumes:
      - .:/app
    user: ${UID}
    working_dir: /app/backend
    environment:
      - BRAVECORE_DATABASE_URL=mysql://neucore:neucore@db/neucore
      - BRAVECORE_TEST_DATABASE_URL=mysql://neucore:neucore@db/neucore_test
    #stdin_open: true
    #tty: true
    #entrypoint: /bin/bash

  java:
    container_name: neucore_java
    image: openjdk:11
    volumes:
      - .:/app
    user: ${UID}

  node:
    container_name: neucore_node
    image: node:10
    volumes:
      - .:/app
    user: ${UID}
    working_dir: /app/frontend

  php-fpm:
    container_name: neucore_php-fpm
    build:
      context: .
      dockerfile: Dockerfile-php-fpm
    user: ${UID}
    volumes:
      - .:/app
    environment:
      - BRAVECORE_DATABASE_URL=mysql://neucore:neucore@db/neucore

  http:
    container_name: neucore_http
    depends_on:
      - php-fpm
    image: nginx:1
    volumes:
      - .:/app
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
