name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: gmp, xdebug, apcu
          ini-values: apc.enable_cli=1
          tools: composer:v1
      - name: Install
        run: cd backend && composer install
      - name: PHPUnit
        env:
          NEUCORE_APP_ENV: dev
          NEUCORE_TEST_DATABASE_URL: 'sqlite:///:memory:'
        run: cd backend && vendor/bin/phpunit
